{
 "title": "Air Quality Overview",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "📊 All Data",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "All Data",
     "type": "timeseries",
     "gridPos": { "h": 13, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "dataset": "aqi_telemetry",
       "rawSql": "SELECT timestamp AS \"time\", concat(metric,\"_\", source) AS \"metric\", value AS \"value\" FROM aqi_telemetry.telemetry WHERE (metric NOT LIKE '%battery%' AND metric NOT LIKE '%time%' AND $__timeFilter(timestamp))"
      }
     ]
    }
   ]
  },
  {
   "title": "⛅ NWS Telemetry",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "nws temp",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 0, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "celsius" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'temp'\n  AND source like '%weather_%'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "nws pressure",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 8, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'pressure'\n  AND source like '%weather_%'\nORDER BY timestamp"
      }
     ]
    },
    {
     "title": "nws humidity",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 2 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'humidity'\n  AND source like '%weather_%'\nORDER BY timestamp"
      }
     ]
    }
   ]
  },
  { "title": "💻 Airthings Telemetry", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 } },
  {
   "title": "co2",
   "type": "stat",
   "description": "Airthings devices use non-dispersive infrared (NDIR) sensors to measure indoor carbon dioxide (\\(CO_{2}\\)) levels, which are primarily produced by human breathing. High indoor \\(CO_{2}\\) levels can negatively impact focus and sleep and are often caused by poor ventilation. Airthings provides real-time data through an app or dashboard and may offer alerts or visual cues to signal when levels are too high, encouraging users to ventilate by opening a window or door. ",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'co2'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "voc",
   "type": "stat",
   "description": "Airthings measures Volatile Organic Compounds (VOCs) using a metal-oxide based sensor that reacts to various chemicals. This sensor can detect most VOCs, although it cannot differentiate between them. VOCs are important to monitor as they can cause serious health effects in both the short and long term.",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'voc'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "radonShortTermAvg",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "Bq/m³" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'radonShortTermAvg'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'humidity'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "temp",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'temp'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "pm1",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'pm1'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "pm25",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'pm25'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "co2",
   "type": "timeseries",
   "description": "Airthings devices use non-dispersive infrared (NDIR) sensors to measure indoor carbon dioxide (\\(CO_{2}\\)) levels, which are primarily produced by human breathing. High indoor \\(CO_{2}\\) levels can negatively impact focus and sleep and are often caused by poor ventilation. Airthings provides real-time data through an app or dashboard and may offer alerts or visual cues to signal when levels are too high, encouraging users to ventilate by opening a window or door. ",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "ppm" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'co2'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "voc",
   "type": "timeseries",
   "description": "Airthings measures Volatile Organic Compounds (VOCs) using a metal-oxide based sensor that reacts to various chemicals. This sensor can detect most VOCs, although it cannot differentiate between them. VOCs are important to monitor as they can cause serious health effects in both the short and long term.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "conppb" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'voc'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "radonShortTermAvg",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "Bq/m³" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'radonShortTermAvg'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "humidity",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'humidity'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "temp",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'temp'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "pm1",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'pm1'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  },
  {
   "title": "pm25",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "fieldConfig": { "defaults": { "unit": "conμgm3" } },
   "targets": [
    {
     "rawSql": "SELECT\n  timestamp AS \"time\",\n  metric AS metric,\n  value\nFROM telemetry\nWHERE\n  $__timeFilter(timestamp)\n  AND metric = 'pm25'\n  AND source like '%home_%'\nORDER BY timestamp"
    }
   ]
  }
 ]
}